### Урок 2. #Профилирование пользователей. Сегментация аудитории: unsupervised learning (clustering, LDA/ARTM), supervised (multi/binary classification)#

In [77]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import itertools

import matplotlib.pyplot as plt

%matplotlib inline

Наши новости

In [2]:
news = pd.read_csv("articles.csv")
print(news.shape)
news.head(3)

(27000, 2)


doc_id                                              title
0       6  Заместитель председателяnправительства РФnСерг...
1    4896  Матч 1/16 финала Кубка России по футболу был п...
2    4897  Форвард «Авангарда» Томаш Заборский прокоммент...

Загрузим пользователей и списки последних прочитанных новостей

In [3]:
users = pd.read_csv("users_articles.csv")
users.head(3)

uid                                        articles
0  u105138  [293672, 293328, 293001, 293622, 293126, 1852]
1  u108690          [3405, 1739, 2972, 1158, 1599, 322665]
2  u108339          [1845, 2009, 2356, 1424, 2939, 323389]

Итак, нам нужно получить векторные представления пользователей на основе прочитанным ими новостей и самих новостей

### 1. Получаем векторные представления новостей

In [4]:
#from gensim.test.utils import common_texts
from gensim.corpora.dictionary import Dictionary

In [8]:
#предобработка текстов
import re
import numpy as np
import nltk
from nltk.corpus import stopwords
#from nltk.tokenize import word_tokenize

from razdel import tokenize # https://github.com/natasha/razdel
#!pip install razdel

import pymorphy2  # pip install pymorphy2

In [9]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Coolver\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [10]:
stopword_ru = stopwords.words('russian')
len(stopword_ru)

151

In [11]:
morph = pymorphy2.MorphAnalyzer()

In [12]:
with open('stopwords.txt') as f:
    additional_stopwords = [w.strip() for w in f.readlines() if w]
stopword_ru += additional_stopwords
len(stopword_ru)

776

In [13]:
def clean_text(text):
    '''
    очистка текста
    
    на выходе очищеный текст
    
    '''
    if not isinstance(text, str):
        text = str(text)
    
    text = text.lower()
    text = text.strip('\n').strip('\r').strip('\t')
    text = re.sub("-\s\r\n\|-\s\r\n|\r\n", '', str(text))

    text = re.sub("[0-9]|[-—.,:;_%©«»?*!@#№$^•·&()]|[+=]|[[]|[]]|[/]|", '', text)
    text = re.sub(r"\r\n\t|\n|\\s|\r\t|\\n", ' ', text)
    text = re.sub(r'[\xad]|[\s+]', ' ', text.strip())
    
    #tokens = list(tokenize(text))
    #words = [_.text for _ in tokens]
    #words = [w for w in words if w not in stopword_ru]
    
    #return " ".join(words)
    return text

cache = {}

def lemmatization(text):
    '''
    лемматизация
        [0] если зашел тип не `str` делаем его `str`
        [1] токенизация предложения через razdel
        [2] проверка есть ли в начале слова '-'
        [3] проверка токена с одного символа
        [4] проверка есть ли данное слово в кэше
        [5] лемматизация слова
        [6] проверка на стоп-слова

    на выходе лист отлемматизированых токенов
    '''

    # [0]
    if not isinstance(text, str):
        text = str(text)
    
    # [1]
    tokens = list(tokenize(text))
    words = [_.text for _ in tokens]

    words_lem = []
    for w in words:
        if w[0] == '-': # [2]
            w = w[1:]
        if len(w)>1: # [3]
            if w in cache: # [4]
                words_lem.append(cache[w])
            else: # [5]
                temp_cach = cache[w] = morph.parse(w)[0].normal_form
                words_lem.append(temp_cach)
    
    words_lem_without_stopwords=[i for i in words_lem if not i in stopword_ru] # [6]
    
    return words_lem_without_stopwords

In [14]:
%%time
#Запускаем очистку текста. Будет долго...
news['title'] = news['title'].apply(lambda x: clean_text(x), 1)

C:\Users\Coolver\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: FutureWarning: Possible nested set at position 39
  from ipykernel import kernelapp as app


Wall time: 21.9 s


In [15]:
%%time
#Запускаем лемматизацию текста. Будет очень долго...
news['title'] = news['title'].apply(lambda x: lemmatization(x), 1)

Wall time: 2min 51s


А теперь в 3 строчки обучим нашу модель

In [16]:
#сформируем список наших текстов, разбив еще и на пробелы
texts = [t for t in news['title'].values]

# Create a corpus from a list of texts
common_dictionary = Dictionary(texts)
common_corpus = [common_dictionary.doc2bow(text) for text in texts]

Что такое common_dictionary и как он выглядит

In [19]:
common_dictionary[10]

'ватутин'

Все просто - это словарь наших слов

Запускаем обучение

In [21]:
%%time
from gensim.models import LdaModel
# Train the model on the corpus.
lda = LdaModel(common_corpus, num_topics=25, id2word=common_dictionary)#, passes=10)

Wall time: 26.7 s


In [22]:
from gensim.test.utils import datapath
# Save model to disk.
temp_file = datapath("model.lda")
lda.save(temp_file)

# Load a potentially pretrained model from disk.
lda = LdaModel.load(temp_file)

Обучили модель. Теперь 2 вопроса:

1. как выглядят наши темы
2. как получить для документа вектор значений (вероятности принадлежности каждой теме)

In [23]:
# Create a new corpus, made of previously unseen documents.
other_texts = [t for t in news['title'].iloc[:3]]
other_corpus = [common_dictionary.doc2bow(text) for text in other_texts]

unseen_doc = other_corpus[2]
print(other_texts[2])
lda[unseen_doc] 

['форвард', 'авангард', 'томаш', 'заборский', 'прокомментировать', 'игра', 'свой', 'команда', 'матч', 'чемпионат', 'кхл', 'против', 'атланта', 'nnnn', 'провести', 'плохой', 'матч', 'нижний', 'новгород', 'против', 'торпедо', 'настраиваться', 'первый', 'минута', 'включиться', 'работа', 'сказать', 'заборский', 'получиться', 'забросить', 'быстрый', 'гол', 'задать', 'хороший', 'темп', 'поединок', 'мочь', 'играть', 'ещё', 'хороший', 'сторона', 'пять', 'очко', 'выезд', 'девять', 'это', 'хороший']


[(3, 0.23890764),
 (12, 0.029663851),
 (13, 0.20678137),
 (20, 0.13838744),
 (23, 0.36815926)]

In [24]:
x=lda.show_topics(num_topics=25, num_words=7,formatted=False)
topics_words = [(tp[0], [wd[0] for wd in tp[1]]) for tp in x]

#Below Code Prints Only Words 
for topic,words in topics_words:
    print("topic_{}: ".format(topic)+" ".join(words))

topic_0: рак общество больной особенность саммит экономика втб
topic_1: форум бизнес фильм технология университет страдать белорусский
topic_2: россия это сша российский который nn система
topic_3: nn страна год египет исследование который город
topic_4: украина суд банк фонд украинский который компания
topic_5: газ турция турецкий необычный грузия грунт европа
topic_6: район восток миссия автомобиль поверхность граница проверка
topic_7: россия год это глава правительство который страна
topic_8: космос определение атмосферный таможенный австралия зеландия ирак
topic_9: млрд рост год компания цена экономика снижение
topic_10: миссия мотив осмотр чечня офицер грозный сергеев
topic_11: год который это человек ребёнок американский также
topic_12: операция рейс конкурс офицер аэропорт супруг палата
topic_13: год млн это стать составить тыс первый
topic_14: парламент сенатор публикация диапазон ноябрь пережить поправка
topic_15: доллар товар теория похоже корь ежедневный козак
topic_16: кило

Очень неплохо - большинство тем вполне можно описать о чем они

Давайте напишем функцию, которая будет нам возвращать векторное представление новости

In [25]:
#text = news['title'].iloc[0]

def get_lda_vector(text):
    unseen_doc = common_dictionary.doc2bow(text)
    lda_tuple = lda[unseen_doc]
    not_null_topics = dict(zip([i[0] for i in lda_tuple], [i[1] for i in lda_tuple]))

    output_vector = []
    for i in range(25):
        if i not in not_null_topics:
            output_vector.append(0)
        else:
            output_vector.append(not_null_topics[i])
    return np.array(output_vector)

In [26]:
topic_matrix = pd.DataFrame([get_lda_vector(text) for text in news['title'].values])
topic_matrix.columns = ['topic_{}'.format(i) for i in range(25)]
topic_matrix['doc_id'] = news['doc_id'].values
topic_matrix = topic_matrix[['doc_id']+['topic_{}'.format(i) for i in range(25)]]
topic_matrix.head(5)

doc_id  topic_0   topic_1   topic_2   topic_3  topic_4  topic_5  topic_6  \
0       6      0.0  0.000000  0.105237  0.023370      0.0      0.0      0.0   
1    4896      0.0  0.000000  0.000000  0.170573      0.0      0.0      0.0   
2    4897      0.0  0.000000  0.000000  0.238853      0.0      0.0      0.0   
3    4898      0.0  0.000000  0.000000  0.115182      0.0      0.0      0.0   
4    4899      0.0  0.101698  0.000000  0.000000      0.0      0.0      0.0   

    topic_7  topic_8  ...  topic_15  topic_16  topic_17  topic_18  topic_19  \
0  0.397733      0.0  ...       0.0       0.0       0.0       0.0       0.0   
1  0.000000      0.0  ...       0.0       0.0       0.0       0.0       0.0   
2  0.000000      0.0  ...       0.0       0.0       0.0       0.0       0.0   
3  0.000000      0.0  ...       0.0       0.0       0.0       0.0       0.0   
4  0.472124      0.0  ...       0.0       0.0       0.0       0.0       0.0   

   topic_20  topic_21  topic_22  topic_23  topic_24  
0  0.012487       0.0  0.000000  0.000000       0.0  
1  0.092049       0.0  0.715369  0.000000       0.0  
2  0.138436       0.0  0.000000  0.368161       0.0  
3  0.044192       0.0  0.000000  0.616029       0.0  
4  0.000000       0.0  0.034919  0.000000       0.0  

[5 rows x 26 columns]

Прекрасно, мы получили вектора наших новостей! И даже умеем интерпретировать получившиеся темы.

Можно двигаться далее

### Следующий шаг - векторные представления пользователей

In [27]:
users.head(3)

uid                                        articles
0  u105138  [293672, 293328, 293001, 293622, 293126, 1852]
1  u108690          [3405, 1739, 2972, 1158, 1599, 322665]
2  u108339          [1845, 2009, 2356, 1424, 2939, 323389]

In [28]:
doc_dict = dict(zip(topic_matrix['doc_id'].values, topic_matrix[['topic_{}'.format(i) for i in range(25)]].values))

In [29]:
doc_dict[293622]

array([0.04688348, 0.08067205, 0.        , 0.12542687, 0.08144744,
       0.        , 0.01923848, 0.02693564, 0.        , 0.        ,
       0.        , 0.0917561 , 0.        , 0.04651381, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.15761624, 0.        , 0.16849624, 0.14650764])

## user_vector = np.mean ##

In [107]:
user_articles_list = users['articles'].iloc[33]

def get_user_embedding(user_articles_list):
    user_articles_list = eval(user_articles_list)
    user_vector = np.array([doc_dict[doc_id] for doc_id in user_articles_list])
    user_vector = np.mean(user_vector, 0)
    return user_vector

In [108]:
user_embeddings = pd.DataFrame([i for i in users['articles'].apply(lambda x: get_user_embedding(x), 1)])
user_embeddings.columns = ['topic_{}'.format(i) for i in range(25)]
user_embeddings['uid'] = users['uid'].values
user_embeddings = user_embeddings[['uid']+['topic_{}'.format(i) for i in range(25)]]

In [109]:
target = pd.read_csv("users_churn.csv")
X = pd.merge(user_embeddings, target, 'left')

In [110]:
#разделим данные на train/test
X_train, X_test, y_train, y_test = train_test_split(X[['topic_{}'.format(i) for i in range(25)]], 
                                                    X['churn'], random_state=0)

In [111]:
logreg = LogisticRegression()
#обучим 
logreg.fit(X_train, y_train)

C:\Users\Coolver\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [112]:
#наши прогнозы для тестовой выборки
preds = logreg.predict_proba(X_test)[:, 1]
preds[:10]

array([0.11944097, 0.00712822, 0.56470352, 0.25466638, 0.0028773 ,
       0.03291145, 0.11017322, 0.09544732, 0.08591435, 0.17249615])

In [113]:
from sklearn.metrics import f1_score, roc_auc_score, precision_score, classification_report, precision_recall_curve, confusion_matrix

**Рассчитаем Precision, Recall, F_score, roc_auc_score**

In [114]:
precision, recall, thresholds = precision_recall_curve(y_test, preds)
fscore = (2 * precision * recall) / (precision + recall)

ix = np.argmax(fscore)
precision_mean, recall_mean, fscore_mean = precision[ix], recall[ix], fscore[ix]

In [115]:
roc_auc_score_mean = roc_auc_score(y_test, preds)

## user_vector = np.median ##

In [116]:
user_articles_list = users['articles'].iloc[33]

def get_user_embedding_median(user_articles_list):
    user_articles_list = eval(user_articles_list)
    user_vector = np.array([doc_dict[doc_id] for doc_id in user_articles_list])
    user_vector = np.median(user_vector, 0)
    return user_vector

In [117]:
user_embeddings = pd.DataFrame([i for i in users['articles'].apply(lambda x: get_user_embedding_median(x), 1)])
user_embeddings.columns = ['topic_{}'.format(i) for i in range(25)]
user_embeddings['uid'] = users['uid'].values
user_embeddings = user_embeddings[['uid']+['topic_{}'.format(i) for i in range(25)]]

In [118]:
target = pd.read_csv("users_churn.csv")
X = pd.merge(user_embeddings, target, 'left')

In [119]:
#разделим данные на train/test
X_train, X_test, y_train, y_test = train_test_split(X[['topic_{}'.format(i) for i in range(25)]], 
                                                    X['churn'], random_state=0)

In [120]:
logreg = LogisticRegression()
#обучим 
logreg.fit(X_train, y_train)

C:\Users\Coolver\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [121]:
#наши прогнозы для тестовой выборки
preds = logreg.predict_proba(X_test)[:, 1]
preds[:10]

array([0.0757842 , 0.01679058, 0.5491474 , 0.24129961, 0.00430817,
       0.03747531, 0.06358791, 0.19771757, 0.03906476, 0.22227242])

**Рассчитаем Precision, Recall, F_score, roc_auc_score**

In [122]:
precision, recall, thresholds = precision_recall_curve(y_test, preds)
fscore = (2 * precision * recall) / (precision + recall)
ix = np.argmax(fscore)
precision_median, recall_median, fscore_median = precision[ix], recall[ix], fscore[ix]

In [123]:
roc_auc_score_median = roc_auc_score(y_test, preds)

## user_vector = np.max ##

In [124]:
def get_user_embedding_max(user_articles_list):
    user_articles_list = eval(user_articles_list)
    user_vector = np.array([doc_dict[doc_id] for doc_id in user_articles_list])
    user_vector = np.max(user_vector, 0)
    return user_vector

In [125]:
user_embeddings = pd.DataFrame([i for i in users['articles'].apply(lambda x: get_user_embedding_max(x), 1)])
user_embeddings.columns = ['topic_{}'.format(i) for i in range(25)]
user_embeddings['uid'] = users['uid'].values
user_embeddings = user_embeddings[['uid']+['topic_{}'.format(i) for i in range(25)]]
user_embeddings.head(3)

uid   topic_0   topic_1   topic_2   topic_3   topic_4   topic_5  \
0  u105138  0.046883  0.165289  0.292869  0.125427  0.677442  0.000000   
1  u108690  0.015807  0.045387  0.368150  0.124850  0.253066  0.000000   
2  u108339  0.000000  0.036189  0.314023  0.235149  0.165786  0.024304   

    topic_6   topic_7  topic_8  ...  topic_15  topic_16  topic_17  topic_18  \
0  0.019238  0.268744      0.0  ...  0.000000   0.01747  0.000000  0.116103   
1  0.052840  0.279367      0.0  ...  0.010254   0.00000  0.068199  0.161523   
2  0.103042  0.184977      0.0  ...  0.000000   0.00000  0.000000  0.169630   

   topic_19  topic_20  topic_21  topic_22  topic_23  topic_24  
0       0.0  0.074564  0.157616  0.184315  0.440324  0.146508  
1       0.0  0.000000  0.022185  0.100790  0.458244  0.136498  
2       0.0  0.000000  0.104956  0.178926  0.169617  0.098926  

[3 rows x 26 columns]

In [126]:
target = pd.read_csv("users_churn.csv")
target.head(3)

uid  churn
0  u107120      0
1  u102277      0
2  u102444      0

In [127]:
X = pd.merge(user_embeddings, target, 'left')
X.head(3)

uid   topic_0   topic_1   topic_2   topic_3   topic_4   topic_5  \
0  u105138  0.046883  0.165289  0.292869  0.125427  0.677442  0.000000   
1  u108690  0.015807  0.045387  0.368150  0.124850  0.253066  0.000000   
2  u108339  0.000000  0.036189  0.314023  0.235149  0.165786  0.024304   

    topic_6   topic_7  topic_8  ...  topic_16  topic_17  topic_18  topic_19  \
0  0.019238  0.268744      0.0  ...   0.01747  0.000000  0.116103       0.0   
1  0.052840  0.279367      0.0  ...   0.00000  0.068199  0.161523       0.0   
2  0.103042  0.184977      0.0  ...   0.00000  0.000000  0.169630       0.0   

   topic_20  topic_21  topic_22  topic_23  topic_24  churn  
0  0.074564  0.157616  0.184315  0.440324  0.146508      0  
1  0.000000  0.022185  0.100790  0.458244  0.136498      1  
2  0.000000  0.104956  0.178926  0.169617  0.098926      1  

[3 rows x 27 columns]

In [128]:
#разделим данные на train/test
X_train, X_test, y_train, y_test = train_test_split(X[['topic_{}'.format(i) for i in range(25)]], 
                                                    X['churn'], random_state=0)

In [129]:
logreg = LogisticRegression()
#обучим 
logreg.fit(X_train, y_train)

C:\Users\Coolver\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [130]:
#наши прогнозы для тестовой выборки
preds = logreg.predict_proba(X_test)[:, 1]
preds[:10]

array([1.40260318e-01, 2.58598620e-04, 7.47081539e-01, 1.94508403e-01,
       4.17670857e-03, 2.13240603e-02, 6.72511480e-02, 5.76560685e-02,
       1.34722273e-02, 1.39069041e-01])

**Рассчитаем Precision, Recall, F_score, roc_auc_score**

In [131]:
precision, recall, thresholds = precision_recall_curve(y_test, preds)
fscore = (2 * precision * recall) / (precision + recall)
ix = np.argmax(fscore)
precision_max, recall_max, fscore_max = precision[ix], recall[ix], fscore[ix]

In [132]:
roc_auc_score_max = roc_auc_score(y_test, preds)

## Сравним результаты ##

In [133]:
table = pd.DataFrame(data={'Metrics':['Precision', 'Recall', 'F-score', 'Roc_auc_score'],
                          'Mean':[precision_mean, recall_mean, fscore_mean, roc_auc_score_mean],
                          'Median':[precision_median, recall_median, fscore_median, roc_auc_score_median],
                          'Max':[precision_max, recall_max, fscore_max, roc_auc_score_max]}, dtype=np.float) 
table

Metrics      Mean    Median       Max
0      Precision  0.750000  0.829060  0.765343
1         Recall  0.844898  0.791837  0.865306
2        F-score  0.794626  0.810021  0.812261
3  Roc_auc_score  0.977238  0.981569  0.979355